In [129]:
import torch

print(torch.__version__)

2.5.1


In [130]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [131]:
scalar.item()

7

In [132]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [133]:
matrix = torch.tensor([[7,8],[9,10]])
matrix.shape

torch.Size([2, 2])

In [134]:
tensor = torch.tensor([
    [
        [1, 2, 3], 
        [4, 5, 6], 
        [7, 8, 9]
    ]
])
tensor.shape

torch.Size([1, 3, 3])

In [135]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [136]:
rand_tensor = torch.rand(3, 4)
rand_tensor

tensor([[0.4723, 0.4258, 0.9807, 0.7424],
        [0.4781, 0.3931, 0.6533, 0.5193],
        [0.7713, 0.7859, 0.9179, 0.7171]])

In [137]:
image_tensor = torch.rand(224, 224, 3)
image_tensor.ndim

3

In [138]:
zero_tensor = torch.zeros(3, 4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [139]:
ones_tensor = torch.ones(3, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [140]:
ones_tensor.dtype

torch.float32

In [141]:
x = torch.arange(1, 11, 1)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
z = torch.zeros_like(input = x)
z

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [143]:
y = torch.ones_like(input = x)
y

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [144]:
float32_tensor = torch.tensor([3, 6, 9], dtype=torch.float32, device =None, requires_grad= False)
float32_tensor.dtype

torch.float32

In [145]:
float16_tensor = torch.tensor([9, 6, 3], dtype=torch.float16, device =None, requires_grad= False)
float16_tensor.dtype

torch.float16

In [146]:
int32_tensor = torch.tensor([3, 3, 3], dtype=torch.int32, device =None, requires_grad= False)
int32_tensor.dtype

torch.int32

In [147]:
int32_tensor * float32_tensor


tensor([ 9., 18., 27.])

In [148]:
float32_tensor.device

device(type='cpu')

In [149]:
tensor_01 = torch.tensor([1,2,3])
tensor_01 + 10


tensor([11, 12, 13])

In [150]:
tensor_01 * 10

tensor([10, 20, 30])

In [151]:
tensor_01 / 10.

tensor([0.1000, 0.2000, 0.3000])

In [152]:
tensor_01 - 10

tensor([-9, -8, -7])

In [153]:
torch.mul(tensor_01, 10)

tensor([10, 20, 30])

In [154]:
torch.add(tensor_01, 10)

tensor([11, 12, 13])

In [155]:
matrix_01 = torch.tensor([[1,2],[3,4]])
matrix_01

tensor([[1, 2],
        [3, 4]])

In [156]:
matrix_02 = torch.tensor([[5,6],[7,8]])
matrix_02

tensor([[5, 6],
        [7, 8]])

In [157]:
torch.matmul(matrix_01, matrix_02)

tensor([[19, 22],
        [43, 50]])

In [158]:
matrix_01 * matrix_02

tensor([[ 5, 12],
        [21, 32]])

In [159]:
tensor_03 = torch.tensor([[1,2,3],[4,5,6]])
tensor_03

tensor([[1, 2, 3],
        [4, 5, 6]])

In [160]:
tensor_04 = torch.tensor([[7, 8],[9,10],[11,12]])
tensor_04

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [161]:
torch.matmul(tensor_03, tensor_04)

tensor([[ 58,  64],
        [139, 154]])

In [162]:
%time

CPU times: user 0 ns, sys: 1 μs, total: 1 μs
Wall time: 1.91 μs


In [163]:
%time
tensor_05 = torch.tensor([1, 2, 3])
sum = 0

for i in range(len(tensor_05)):
    sum += tensor_05[i] * tensor_05[i]
    
print(sum)

CPU times: user 1 μs, sys: 1 μs, total: 2 μs
Wall time: 2.15 μs
tensor(14)


In [164]:
%time
torch.matmul(tensor_05, tensor_05)

CPU times: user 4 μs, sys: 1 μs, total: 5 μs
Wall time: 7.87 μs


tensor(14)

In [165]:
tensor_a = torch.tensor([
    [1, 2], 
    [3, 4], 
    [5, 6]
])

tensor_b = torch.tensor([
    [7, 8], 
    [9, 10], 
    [11, 12]
])


In [166]:
tensor_b_T = tensor_b.T

In [167]:
tensor_b_T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [168]:
torch.matmul(tensor_a, tensor_b_T).shape

torch.Size([3, 3])

In [169]:
tensor_a.min()
torch.min(tensor_a)

tensor(1)

In [170]:
tensor_a.max()

tensor(6)

In [171]:
tensor_a.sum()

tensor(21)

In [172]:
tensor_a.dtype

torch.int64

In [173]:
tensor_c = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor_c.dtype

torch.float32

In [174]:
torch.mean(tensor_c)

tensor(2.)

In [175]:
tensor_a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [176]:
tensor_a.min()

tensor(1)

In [177]:
tensor_a.argmin()

tensor(0)

In [178]:
tensor_a.max()

tensor(6)

In [179]:
tensor_a.argmax()

tensor(5)

In [180]:
num_tensor = torch.arange(0, 100, 1).to(dtype=torch.float32)
num_tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
        56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
        70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
        84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.,
        98., 99.])

In [181]:
print(f"min: ", num_tensor.min())
print(f"position min: ", num_tensor.argmin())

print(f"max: ", num_tensor.max())
print(f"position max: ", num_tensor.argmax())

print(f"mean: ", num_tensor.mean())

min:  tensor(0.)
position min:  tensor(0)
max:  tensor(99.)
position max:  tensor(99)
mean:  tensor(49.5000)


In [183]:
num_tensor
num_tensor.shape

torch.Size([100])

In [191]:
num_tensor_reshaped = num_tensor.reshape(50, 2)
num_tensor_reshaped

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.],
        [16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.],
        [24., 25.],
        [26., 27.],
        [28., 29.],
        [30., 31.],
        [32., 33.],
        [34., 35.],
        [36., 37.],
        [38., 39.],
        [40., 41.],
        [42., 43.],
        [44., 45.],
        [46., 47.],
        [48., 49.],
        [50., 51.],
        [52., 53.],
        [54., 55.],
        [56., 57.],
        [58., 59.],
        [60., 61.],
        [62., 63.],
        [64., 65.],
        [66., 67.],
        [68., 69.],
        [70., 71.],
        [72., 73.],
        [74., 75.],
        [76., 77.],
        [78., 79.],
        [80., 81.],
        [82., 83.],
        [84., 85.],
        [86., 87.],
        [88., 89.],
        [90., 91.],
        [92., 93.],
        [94., 95.],
        [96., 97.],
        [98., 99.]])

In [193]:
z = num_tensor.view(50, 2)
z

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.],
        [16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.],
        [24., 25.],
        [26., 27.],
        [28., 29.],
        [30., 31.],
        [32., 33.],
        [34., 35.],
        [36., 37.],
        [38., 39.],
        [40., 41.],
        [42., 43.],
        [44., 45.],
        [46., 47.],
        [48., 49.],
        [50., 51.],
        [52., 53.],
        [54., 55.],
        [56., 57.],
        [58., 59.],
        [60., 61.],
        [62., 63.],
        [64., 65.],
        [66., 67.],
        [68., 69.],
        [70., 71.],
        [72., 73.],
        [74., 75.],
        [76., 77.],
        [78., 79.],
        [80., 81.],
        [82., 83.],
        [84., 85.],
        [86., 87.],
        [88., 89.],
        [90., 91.],
        [92., 93.],
        [94., 95.],
        [96., 97.],
        [98., 99.]])

In [194]:
num_tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
        56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
        70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
        84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.,
        98., 99.])

In [196]:
z = num_tensor.view(1, 100)
z

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
         28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
         42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
         56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
         70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
         84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.,
         98., 99.]])

In [197]:
num_tensor == z

tensor([[True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True]])

In [198]:
z[]

SyntaxError: invalid syntax (932219487.py, line 1)

In [199]:
z[0]

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
        56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
        70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
        84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.,
        98., 99.])

In [200]:
z[0, :]

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
        56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
        70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
        84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.,
        98., 99.])

In [202]:
z[:, 0] = -4

In [203]:
z

tensor([[-4.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
         28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
         42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
         56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
         70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
         84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.,
         98., 99.]])

In [204]:
num_tensor

tensor([-4.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
        56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
        70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
        84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.,
        98., 99.])

In [208]:
num_tensor_stacked = torch.stack((num_tensor, num_tensor), dim = 0)
num_tensor_stacked

tensor([[-4.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
         28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
         42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
         56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
         70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
         84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97.,
         98., 99.],
        [-4.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
         28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
         42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
         56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
         70., 71., 72., 73., 74.

In [214]:
x = torch.rand(2, 1, 3, 1)
print(f"original shape: {x.shape}")
x

original shape: torch.Size([2, 1, 3, 1])


tensor([[[[0.9260],
          [0.3784],
          [0.4477]]],


        [[[0.9692],
          [0.4309],
          [0.8406]]]])

In [215]:
y = x.squeeze()
print(f"squeezed shape: {y.shape}")
y

squeezed shape: torch.Size([2, 3])


tensor([[0.9260, 0.3784, 0.4477],
        [0.9692, 0.4309, 0.8406]])

In [218]:
z = y.unsqueeze(dim = 2)
print(f"unsqueezed shape: {z.shape}")
z

unsqueezed shape: torch.Size([2, 3, 1])


tensor([[[0.9260],
         [0.3784],
         [0.4477]],

        [[0.9692],
         [0.4309],
         [0.8406]]])

In [219]:
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [220]:
x

tensor([[[ 1.0193, -0.5075,  0.2065,  0.4261,  0.4291],
         [ 0.4260, -1.4120,  0.2937,  0.3854, -0.4052],
         [-1.3502,  0.2831, -1.5733,  0.9733,  0.2429]],

        [[-0.8919,  0.2068,  0.0291,  1.1583, -0.1833],
         [-0.5680,  1.0777,  0.3955,  0.3675,  1.9484],
         [-0.7096,  0.0792, -0.2453, -0.1071, -0.2254]]])

In [229]:
y = x.permute(2, 0, 1)
y.size()

torch.Size([5, 2, 3])

In [224]:
y

tensor([[[ 1.0193,  0.4260, -1.3502],
         [-0.8919, -0.5680, -0.7096]],

        [[-0.5075, -1.4120,  0.2831],
         [ 0.2068,  1.0777,  0.0792]],

        [[ 0.2065,  0.2937, -1.5733],
         [ 0.0291,  0.3955, -0.2453]],

        [[ 0.4261,  0.3854,  0.9733],
         [ 1.1583,  0.3675, -0.1071]],

        [[ 0.4291, -0.4052,  0.2429],
         [-0.1833,  1.9484, -0.2254]]])

In [234]:
x = torch.arange(1, 10, 1).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [235]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [244]:
x[0, 2, 2]


tensor(9)

In [247]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [248]:
x[:,1, 1]

tensor([5])

In [250]:
x[0, 0, :] == x[0][0]

tensor([True, True, True])

In [251]:
x.size()

torch.Size([1, 3, 3])

In [253]:
x[0, 2, 2]

tensor(9)

In [256]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [263]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [264]:
import numpy as np

In [265]:
array_01 = np.arange(1, 20, 1)
array_01

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [266]:
tensor_01 = torch.from_numpy(array_01)
tensor_01

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [267]:
array_02 = torch.Tensor.numpy(tensor_01)
array_02

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [269]:
array_01.dtype, tensor_01.dtype

(dtype('int64'), torch.int64)

In [272]:
tensor_01 = torch.ones(10)
tensor_01.dtype

torch.float32

In [273]:
array_01 = torch.Tensor.numpy(tensor_01)
array_01.dtype

dtype('float32')

In [274]:
tensor_03 = torch.rand(3, 3)
tensor_03

tensor([[0.8175, 0.2269, 0.7854],
        [0.2685, 0.3270, 0.1846],
        [0.1789, 0.5518, 0.5594]])

In [ ]:
tensor_03 = torch.rand(3, 3)
tensor_03

In [275]:
random_tensor_01 = torch.rand(3, 4)
random_tensor_02 = torch.rand(3, 4)

print(f"random_tensor_01: {random_tensor_01}")
print(f"random_tensor_02: {random_tensor_02}")
print(f"equality check: ", random_tensor_01 == random_tensor_02)

random_tensor_01: tensor([[0.4530, 0.2678, 0.7220, 0.1585],
        [0.2716, 0.0842, 0.1369, 0.2905],
        [0.7605, 0.3378, 0.8897, 0.8498]])
random_tensor_02: tensor([[0.7882, 0.2025, 0.7749, 0.8368],
        [0.9833, 0.9928, 0.6243, 0.2383],
        [0.9557, 0.7791, 0.4691, 0.9496]])
equality check:  tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [282]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_03 = torch.rand(3, 4)
random_tensor_04 = random_tensor_03.clone()

print(f"random_tensor_03 w/ manual seed: {random_tensor_03}")
print(f"random_tensor_04 w/ manual seed: {random_tensor_04}")
print(f"equality check: ", random_tensor_03 == random_tensor_04)


random_tensor_03 w/ manual seed: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
random_tensor_04 w/ manual seed: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
equality check:  tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [284]:
torch.cuda.is_available()

False

In [289]:
device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [286]:
torch.cuda.device_count()

0

In [287]:
tensor_06 = torch.tensor([1,2,3], device = device)
print(f"tensor_06: {tensor_06}")
print(f"tensor_06 device: {tensor_06.device}")

tensor_06: tensor([1, 2, 3])
tensor_06 device: cpu


In [288]:
tensor_07_on_cpu = tensor_06.to(device)
print(f"tensor_07_on_cpu: {tensor_07_on_cpu}")
print(f"tensor_07_on_cpu device: {tensor_07_on_cpu.device}")

tensor_07_on_cpu: tensor([1, 2, 3])
tensor_07_on_cpu device: cpu
